### ISSUE TITLE
convert CSS pdf's to HTML

### ISSUE THREAD

**Issue by nickdesaulniers** [Mozilla-NTU/slidesMay2015#3]
https://github.com/Mozilla-NTU/slides2014/blob/gh-pages/slides/day1-section3-css-basic.pdf
and
https://github.com/Mozilla-NTU/slides2014/blob/gh-pages/slides/day2-section2-css-advanced.pdf

need to be converted to HTML reveal.js slides.  There's a template here:
https://github.com/Mozilla-NTU/slidesMay2015/blob/gh-pages/slides/template.html

The resulting pages should live in:
https://github.com/Mozilla-NTU/slidesMay2015/tree/gh-pages/slides

and be linked from:
https://github.com/Mozilla-NTU/slidesMay2015/blob/gh-pages/slides/day1-section1-intro.html

**Comment by debloper** [comment]
Fixed with #9 & #12
